version: '3.5'
services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: ossec
            POSTGRES_PASSWORD: ossec
            POSTGRES_DB: ossec
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:5432:5432

    api:
        environment:
            DJANGO_DEBUG: 1
            DB_HOST: ossec-rest_postgres_1
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - 127.0.0.1:8080:8080

volumes:
    postgres:
